FROM nodesource/node
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y
RUN apt-get install -y git-core

ENV NODE_ENV production
ENV NODE_PATH /opt/{{appName}}
WORKDIR /opt/{{appName}}
EXPOSE {{port}}
#USER {{appName}}

ADD package.json  /opt/{{appName}}/package.json
RUN npm install --production
ADD bower.json  /opt/{{appName}}/bower.json
RUN ./node_modules/.bin/bower --allow-root --config.analytics=false install

ADD . /opt/{{appName}}
CMD ["./app/server.js"]
