#!/bin/bash
export DOCKER_HOST=tcp://localhost:2375
container="mjournal_db"
user=postgres
backup_dir="/var/local/mjournal_db_backups"

do_backup() {
  docker exec "${container}" \
    pg_dumpall --user="${user}" --host=localhost --clean --no-password > "$1"
  bzip2 "$1"
}

prepare() {
  export DATE=$(date +%Y-%m-%d)
  mkdir -p "${backup_dir}"
}

choose_backups() {
  # date +%d: Date of the Month e.g. 27
  if [[ $(date +%d) == "01" ]]; then
    export MONTHLY=yes
  fi
}

backup_daily() {
  echo "Taking daily backup"
  do_backup "${backup_dir}/${DATE}.daily.sql"
}

backup_monthly() {
  if [[ -z "${MONTHLY}" ]]; then
    return 0
  fi
  echo "Taking monthly backup"
  do_backup "${backup_dir}/$DATE.monthly.sql"
}

delete_stale_backups() {
  find "${backup_dir}" -name '*.daily.sql.bz2' -ctime +30 -print
  find "${backup_dir}" -name '*.monthly.sql.bz2' -ctime +90 -print
}

main() {
  prepare
  choose_backups
  backup_daily
  backup_monthly
  delete_stale_backups
}

main
