# https://registry.hub.docker.com/u/nodesource/node/
FROM nodesource/node:wheezy
#get the slow/big stuff done early so the cache is rarely invalidated
ENV DEBIAN_FRONTEND noninteractive

#npm prereqs: build_essential, python
#bower prereqs: git-core
RUN apt-get update && apt-get install -y \
  build-essential \
  git-core \
  python

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /opt/{{appName}}
ADD package.json  /opt/{{appName}}/package.json
ADD bower.json  /opt/{{appName}}/bower.json
RUN npm install --production
RUN ./node_modules/.bin/bower --allow-root --config.analytics=false install

#OK, all the slow stuff has been run and hopefully cached
RUN cd node_modules && ln -nsf ../app

ADD app /opt/{{appName}}/app
ADD wwwroot /opt/{{appName}}/wwwroot
ADD config.default.js /opt/{{appName}}/config.default.js
ENV NODE_ENV production
EXPOSE {{port}} 22
USER www-data
CMD ["/opt/{{appName}}/app/server.js"]
