#I buy some of this rationale
#https://github.com/phusion/baseimage-docker
FROM phusion/baseimage:0.9.13

ENV HOME /root
#get the slow/big stuff done early so the cache is rarely invalidated
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y

#npm prereqs: build_essential, python
#bower prereqs: git-core
# RUN curl -sL https://deb.nodesource.com/setup | sudo bash -
RUN apt-get install -y \
  build-essential \
  python \
  git-core

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#keep npm and bower early for caching goodness
ADD http://nodejs.org/dist/v{{nodeVersion}}/node-v{{nodeVersion}}-linux-x64.tar.gz \
  /home/app/node-v{{nodeVersion}}-linux-x64.tar.gz
WORKDIR /home/app
RUN mkdir node && \
  cd node && \
  tar --strip-components=1 --extract --gzip --file \
  ../node-v{{nodeVersion}}-linux-x64.tar.gz
ENV PATH /home/app/node/bin:/home/app/node_modules/.bin:/usr/bin:/bin:/usr/sbin:/sbin
ADD package.json  /home/app/package.json
ADD bower.json  /home/app/bower.json
RUN npm install --production
RUN bower --allow-root --config.analytics=false install

#OK, all the slow stuff has been run and hopefully cached
RUN cd node_modules && ln -nsf ../app

ADD deploy/docker_insecure.pub /root/.ssh/authorized_keys
RUN mkdir /etc/service/{{appName}}
ADD deploy/{{appName}}-run.sh /etc/service/{{appName}}/run

ADD app /home/app/app
ADD wwwroot /home/app/wwwroot
ADD config.default.js /home/app/config.default.js
EXPOSE {{port}} 22
CMD ["/sbin/my_init"]
